Repository Refemi/refemi_api, pull requests merged in 2022-01, with the labels that each got.

#10 17 dashboard admin
  .gitignore
  controllers/adminControllers.js
  controllers/categoriesController.js
  controllers/config/dev.js
  controllers/config/index.js
  controllers/config/nodemailer.js
  controllers/config/prod.js
  controllers/contactController.js
  controllers/counterController.js
  controllers/referencesController.js
  controllers/searchControllers.js
  controllers/sendControllers.js
  controllers/themeController.js
  controllers/userControllers.js
  middlewares/authJwt.js
  middlewares/checkRight.js
  middlewares/protect.js
  package.json
  routers/adminRouter.js
  routers/categoriesRouter.js
  routers/contactRouter.js
  routers/counterRouter.js
  routers/loginRouter.js
  routers/referencesRouter.js
  routers/registerRouter.js
  routers/searchRouter.js
  routers/sendRouter.js
  routers/themesRouter.js
  server.js
  utils/killCookie.js
Labels: enhancement

#12 17 dashboard admin
  controllers/counterController.js
  controllers/referencesController.js
  package.json
  routers/referencesRouter.js
Labels: enhancement

#25 22 themes disappeared
  package.json
  src/v1/components/references/referencesController.js
Labels: bug, priority: cool

#27 update: returns an error if also rowCount is zero
  src/v1/components/references/referencesController.js
Labels: on hold until another ticket is solved, code level up

#23 21 unable to connect
  package.json
  src/v1/components/auth/auth.js
  src/v1/components/auth/authController.js
Labels: bug, priority: burning hot

#28 updated referencesByTheme request
  src/v1/components/references/referencesController.js
Labels: enhancement, to be tested please!
